config/routes.rb
Rails.application.routes.draw do
  get 'search/search'

  match 'search/convert_pdf' => 'search#convert_pdf', format: :pdf, via: [:get, :post]
  match 'search/convert_pdf_wicked' => 'search#convert_pdf_wicked', format: :pdf, via: [:get, :post]
  root 'search#search'

  resources :search 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def uniq_by
    hash, array = {}, []
    each { |i| hash[yield(i)] ||= (array << i) }
    array
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/convert_pdf_wicked.html.erb
<div class="container">
	<div>
		<h1>
			<b><%= params['word'].capitalize %>
			</b>
		</h1>
	</div>
	<div>
		<div class="image">
			<%= image_tag params['picture'] %>
		</div>	
		<div class="top_30"> <b class = "act-as-h3">STEP 1:</b> Say <i><b><%= params['word'].capitalize %> </b></i> 3 times</div>
		<div class="top_30"><b class = "act-as-h3">STEP 2: </b><i><b><%= params['word'].capitalize %> </b></i> used in context</div>
		<% (0..params["examples_count"].to_i).each_with_index do |value,index| %>
			<% if params["example_#{index}_check"] == "1" %>
				<% example = eval(params["example_#{index}"]) %>
				<div class="width_100">
				<%= example['text']%>
				</div>
			<% end %>
		<% end %>
		<div class="top_30"><b class = "act-as-h3">STEP 3: </b><i><b><%= params['word'].capitalize %></b></i> definition</div>
		<% (0..params["definitions_count"].to_i).each_with_index do |value,index| %>
			<% if params["part_of_speech_#{index}_check"] == "1" %>
				<% definition = eval(params["part_of_speech_#{index}"]) %>
				<div class="width_100">
					<%= definition['partOfSpeech'] + " - " + definition['text']%>
				</div>
			<% end %>
		<% end %>
		<div class="top_30"><b class = "act-as-h3">STEP 4: </b><i><b><%= params['word'].capitalize %></b></i> elementary definition</div>
		<% (0..params["elem_def_count"].to_i).each_with_index do |value,index| %>
			<% if params["elem_def_#{index}_check"] == "1" %>
				<% elementary_definition = eval(params["elem_def_#{index}"]) %>
					<div class="width_100">
						<%= elementary_definition['word'] + ' - ' + elementary_definition['grammar'] + ' - ' + elementary_definition['text'] %>
					</div>
			<% end %>
		<% end %>
		<div class="top_30"><b class = "act-as-h3">STEP 5: </b><i><b><%= params['word'].capitalize %></b></i> challenges</div>
		<% (0..params["definitions_count"].to_i).each_with_index do |value,index| %>
			<% if params["relationship_type_#{index}_check"] == "1" %>
				<% related_words = eval(params["relationship_type_#{index}"]) %>
				<div class="width_100">
					<%= related_words['relationshipType'] + " - " + related_words['words'].join(",") %>
				</div>
			<% end %>
		<% end %>
		<div class="top_30"><b class = "act-as-h3">STEP 6: </b><i><b><%= params['word'].capitalize %></b></i> student activity</div>
		<% if params["student_activity"] %>
			<div class="width_100">
				<%= params["student_activity"] %>
			</div>
		<% end %>
		<div class="top_30"><b class = "act-as-h3">STEP 7: </b><i><b><%= params['word'].capitalize %></b></i> mastery activity</div>
			<% if params["mastery_activity"] %>
			<div class="width_100">
				<%= params["mastery_activity"] %>
			</div>
		<% end %>
	</div>
</div>

app/views/search/search.html.erb
<div class="container">
  <%= form_tag(root_path, :method => "get", class: "form-inline", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search words" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
             of using a Rails form helper -->
      <button class="btn btn-primary" type="submit">Search</button>
    </div>
  <% end %>

  <% if params[:search] %>
    <%= form_tag search_convert_pdf_wicked_path(format: "pdf"), :method => :post do %>
      <div class="row">
        <h3><blockquote> Results </blockquote></h3> 
        <div class="col-xs-1"></div>
        <p> <b> Word </b> - <%= @word %></p>
        <%= hidden_field_tag "word", @word %>
        
        <h3><blockquote> <%# check_box_tag 'definition_check', 1, false, class: 'check_boxes' %>Definitions </blockquote></h3>
        <%= hidden_field_tag "definitions_count", @definitions.count %>
        <% @definitions.each_with_index do |x,i| %>
        <div class="col-xs-1"></div>
          <p>
            <%= check_box_tag "part_of_speech_#{i}_check", 1, false, class: 'check_boxes' %>
            <%= hidden_field_tag "part_of_speech_#{i}", x %>
            <b><%= x['partOfSpeech'] %></b> - <%= x['text'] %>  
          </p>
        <% end %>

        <h3><blockquote> <%# check_box_tag 'pronounciation_check',1, false, class: 'check_boxes' %>Pronounciations </blockquote></h3>
        <%= hidden_field_tag "pronounciations_count", @pro_results.count %>
        <% @pro_results.each_with_index do |x,i| %>
          <%= hidden_field_tag "raw_type_#{i}", x %>
          <div class="col-xs-1"></div>
          <p><%= check_box_tag "raw_type_#{i}_check", 1, false, class: 'check_boxes' %> <%= x['rawType'] %> - <%= x['raw']%></p>
        <% end %>

        <h3><blockquote> <%# check_box_tag 'related_words_check',1, false, class: 'check_boxes' %>Related Words</blockquote> </h3>
        <%= hidden_field_tag "related_words_count", @rel_results.count %>
        <% @rel_results.each_with_index do |x,i| %>
          <div class="col-xs-1"></div>
          <%= hidden_field_tag "relationship_type_#{i}", x %>
          <p><%= check_box_tag "relationship_type_#{i}_check", 1, false, class: 'check_boxes' %><%= x['relationshipType']%> = <%= x['words'].join(",") %></p>
        <% end %>

        <h3><blockquote> <%= check_box_tag 'top_example_check',1, false, class: 'check_boxes' %>Top Example </blockquote></h3>
        <%= hidden_field_tag "top_example", @top_results['text'] %>
        <div class="col-xs-1"></div>
        <p> <%= @top_results['text'] %> </p>

        <h3> <blockquote><%# check_box_tag 'example_check',1, false, class: 'check_boxes' %>Example </blockquote></h3>
        <%= hidden_field_tag "examples_count", @example_results['examples'].count %>
        <% @example_results['examples'].each_with_index do |x, i| %>
          <%= hidden_field_tag "example_#{i}", x %>
          <div class="col-xs-1"></div>
          <p><%= check_box_tag "example_#{i}_check", 1, false, class: 'check_boxes' %> <%= x['text']%></p>
        <% end %> 

        <h3> <blockquote>Audio </blockquote></h3>
        <% @audio_results.each do |x| %>
          <audio controls><source src="<%= x['fileUrl']%>" type="audio/mpeg"></audio>
        <% end %> 

        <h3> <blockquote><%# check_box_tag 'pictures_check',1, false, class: 'check_boxes' %>Pictures </blockquote></h3>
        <div class="pull-left">
          <%= hidden_field_tag "pictures_count", @pic_results['payload'].count %>
          <% @pic_results['payload'].each_with_index do |x, i| %>
            <%= hidden_field_tag "picture_#{i}", x %>
            <span class="list_images">
              <%= radio_button_tag "picture", x['svg']['png_thumb'], false, class: 'check_boxes' %>
              <img src="<%= x['svg']['png_thumb'] %>" height="150px">
              </span>
          <% end %>
        </div>
        <div class="pull-left">
          <h3> <blockquote><%#= check_box_tag 'mw_dictionary_check',1, false, class: 'check_boxes' %>MW Dictionary API</blockquote></h3>

          <%= hidden_field_tag "mw_dictionaries_count", @xml.css('entry').count %>
          <% @xml.css('entry').each_with_index do |x,i| %>
            <%= hidden_field_tag "hw_#{i}", x.css('hw').text %>
            <p><%= check_box_tag "hw_#{i}_check", 1, false, class: 'check_boxes' %> <%= x.css('hw').text %> - <%= x.css('fl').text %> - <%= x.css('dt').first.present? ? x.css('dt').first.text : "" %>  </p>
          <% end %>
          <p></p>
        </div>
        <div class="pull-left">
          <h3> <blockquote><%#= check_box_tag 'mw_dictionary_check',1, false, class: 'check_boxes' %>Elementary Definition</blockquote></h3>

          <%= hidden_field_tag "elem_def_count", @xml.css('entry').count %>
          <% @elementary_xml.css('entry').each_with_index do |x,i| %>
            <% if x.css('hw').text == params[:search] %>
              <% text = x.css('dt').first.present? ? x.css('dt').first.text.gsub("'",'') : "" %>
              <%= hidden_field_tag "elem_def_#{i}", "{'word' => '#{x.css('hw').text}', 'grammar' => '#{x.css('fl').text}', 'text' => '#{text}'}" %>
              <p><%= check_box_tag "elem_def_#{i}_check", 1, false, class: 'check_boxes' %> <%= x.css('hw').text %> - <%= x.css('fl').text %> - <%= text %>  </p>
            <% end %>
          <% end %>
          <p></p>
        </div>
        <div class="col-md-12">
            <h3> <blockquote>Student Activity</blockquote></h3>
            <%= hidden_field_tag "student_activity_count", 3 %>
            <%= hidden_field_tag "" %>
            <p><%= radio_button_tag "student_activity", "This is a Student Activity 1", false, class: 'check_boxes' %>
            This is a Student Activity 1</p>
            <p><%= radio_button_tag "student_activity", "This is a Student Activity 2", false, class: 'check_boxes' %>
            This is a Student Activity 2</p>
            <p><%= radio_button_tag "student_activity", "This is a Student Activity 3", false, class: 'check_boxes' %>
            This is a Student Activity 3</p>
            <p></p>
        </div>
        <div class="col-md-12">
            <h3> <blockquote>Mastery Activity</blockquote></h3>
            <%= hidden_field_tag "mastery_activity_count", 3 %>
            <%= hidden_field_tag "" %>
            <p><%= radio_button_tag "mastery_activity", "This is a Mastery Activity 1", false, class: 'check_boxes' %>This is a Mastery Activity 1</p>
            <p><%= radio_button_tag "mastery_activity", "This is a Mastery Activity 2", false, class: 'check_boxes' %>This is a Mastery Activity 2</p>
            <p><%= radio_button_tag "mastery_activity", "This is a Mastery Activity 3", false, class: 'check_boxes' %>This is a Mastery Activity 3</p>
            <p></p>
        </div>
      </div>
      <%= submit_tag "Export as PDF", :class => 'btn btn-primary' %>
    <% end %>
  <% end %>
</div>

<br />
<br />